### ISSUE TITLE
Problems trying to run the project 

### ISSUE THREAD

**Issue by goxr3plus** [dlemmermann/JProCalendarFX#3]
I have cloned the project and trying to run it .

Gradle Version used is : 

```
C:\Users\GOXR3PLUS\Desktop\rush\JProCalendarFX>gradle -v

------------------------------------------------------------
Gradle 4.2
------------------------------------------------------------

Build time:   2017-09-20 14:48:23 UTC
Revision:     5ba503cc17748671c83ce35d7da1cffd6e24dfbd

Groovy:       2.4.11
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          1.8.0_151 (Oracle Corporation 25.151-b12)
OS:           Windows 10 10.0 amd64
```

I am using cmd but i am keep getting the below errors for some unknown reason .. 

```
C:\Users\GOXR3PLUS\Desktop\rush\JProCalendarFX>gradle jproRestart
Starting a Gradle Daemon, 1 incompatible and 1 stopped Daemons could not be reused, use --status for details

> Configure project :
The Task.leftShift(Closure) method has been deprecated and is scheduled to be removed in Gradle 5.0. Please use Task.doLast(Action) instead.
        at build_b3azosk7ze54l2fchuupw1c6k.run(C:\Users\GOXR3PLUS\Desktop\rush\JProCalendarFX\build.gradle:47)
        (Run with --stacktrace to get the full stack trace of this deprecation warning.)

> Task :jproStop
The Server is not running!

> Task :jproStart

Server could not be started. Error-Code: 0

Server could not be started. Error-Code: 0

Server could not be started. Error-Code: 0

Server could not be started. Error-Code: 0

Server could not be started. Error-Code: 0

Server could not be started. Error-Code: 0

Server could not be started. Error-Code: 0

Server could not be started. Error-Code: 0

Server could not be started. Error-Code: 0
<=========----> 75% EXECUTING [22s]
```

**Comment by dlemmermann** [comment]
I always used jproRun, which worked for me.

**Comment by goxr3plus** [comment]
Can it be a Gradle Version issue ? I have also tried ```jproRun``` and the below error appears ( I started a fresh clone to try this ) : 

```
C:\Users\GOXR3PLUS\Desktop\rush\JProCalendarFX>gradle jproRun
Starting a Gradle Daemon, 1 stopped Daemon could not be reused, use --status for details

> Configure project :
The Task.leftShift(Closure) method has been deprecated and is scheduled to be removed in Gradle 5.0. Please use Task.doLast(Action) instead.
        at build_b3azosk7ze54l2fchuupw1c6k.run(C:\Users\GOXR3PLUS\Desktop\rush\JProCalendarFX\build.gradle:47)
        (Run with --stacktrace to get the full stack trace of this deprecation warning.)

com.jpro.boot.JProBoot: got exception: java.lang.ClassNotFoundException: play.core.server.ProdServerStart
java.lang.ClassNotFoundException: play.core.server.ProdServerStart
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at com.jpro.boot.JProBoot.startJPro(JProBoot.java:96)
        at com.jpro.boot.JProBoot.main(JProBoot.java:36)

> Task :jproRun

Server could not be started. Error-Code: 0

Server could not be started. Error-Code: 0

Server could not be started. Error-Code: 0

Server could not be started. Error-Code: 0

Server could not be started. Error-Code: 0

Server could not be started. Error-Code: 0

Server could not be started. Error-Code: 0

Server could not be started. Error-Code: 0
<==========---> 80% EXECUTING [40s]
```

**Comment by FlorianKirmaier** [comment]
I don't think it's related to the gradle version. I'm using gradle 4.1 and it's working for me.
I tested it on Windows and i can reproduce the issue. 
Are you using Windows? 
It's a jpro-issue im going to fix it soon.

**Comment by FlorianKirmaier** [comment]
@goxr3plus 
I did just release a new snapshot-build for jpro. 
It should fix the issue on Windows.
Can you retry it? You can add the following argument to gradle, force the reload of the dependencies: `--refresh-dependencies`

**Comment by goxr3plus** [comment]
@FlorianKirmaier Thank you very much now it runs . But there is a problem ...
Is it normal for the JProCalendarFX web application to be so extremely slow [ Really almost unusable ] ? 

When JPro will be an official product and pass Beta phase ? Where i can find news ?

**Comment by dlemmermann** [comment]
Currently it runs best when using Chrome.

**Comment by FlorianKirmaier** [comment]
@goxr3plus 
It shouldn't be very slow. Going to the year-view the first time is usually slow. But otherwise it should be quite responsive. Which Browser are you using?

About the release:
The release is basically finished. You can find a minimal sample-project here: https://github.com/jpro-one/HelloJPro
We are working on a new WebPage which will be release together with an offical release.
